project:
  type: website
  resources:
    - "data/*.csv"

website:
  title: "RABO Workshop"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - text: "Details"
        menu:
          - text: "Instructors"
            href: details/instructors.qmd
          - text: "Schedule"
            href: details/schedule.qmd
          - text: "Resources"
            href: details/resources.qmd
      - text: "Day 1"
        menu:
          - text: "Ecology"
            href: slides/01_rabo_ecology.qmd
          - text: "Slides 1"
            href: slides/Day1A_Slides.qmd
      - icon: github
        href: https://www.github.com/ryanpeek/rabo-workshop
  search: false
  page-footer: "written in Quarto by R. Peek"

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css
