project:
  type: website
  resources:
    - "data/*.csv"

website:
  title: "RABO Workshop"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - text: "Details"
        menu:
          - text: "Instructors"
            href: Details/instructors.qmd
          - text: "Schedule"
            href: Details/schedule.qmd
          - text: "Resources"
            href: Details/resources.qmd
      - text: "Slides"
        menu:
          - text: "Intro"
            href: slides/D1_rabo_00.qmd
          - text: "Natural History"
            href: slides/D1_rabo_01.qmd
          - text: "Status"
            href: slides/D1_rabo_03.qmd
          - text: "Un-Natural History"
            href: slides/D1_rabo_02.qmd
          - text: "Habitat"
            href: slides/D1_rabo_04.qmd
          - text: "---"
          - text: "Ecology"
            href: slides/D1_rabo_06.qmd
          - text: "Climate & Phenology"
            href: slides/D1_rabo_05.qmd
          - text: "Survey Methods"
            href: slides/D1_rabo_07.qmd
          - text: "Conservation"
            href: slides/D1_rabo_08.qmd
            
      - icon: github
        href: https://www.github.com/ryanpeek/rabo-workshop
  search: false
  page-footer: "written in Quarto by R. Peek"

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css
