project:
  type: website
  output-dir: _site
  resources:
    - "data/*.csv"

website:
  title: "RABO Workshop"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - text: "Details"
        menu:
          - text: "Instructors"
            href: Details/instructors.qmd
          - text: "Schedule"
            href: Details/schedule.qmd
          - text: "Resources"
            href: Details/resources.qmd
      - text: "Slides"
        menu:
          - text: "Intro"
            href: slides/D1_rabo_00.qmd
          - text: "Natural History"
            href: slides/rabo_01_natural_history.qmd
          - text: "Status"
            href: slides/rabo_02_status.qmd
          - text: "Un-Natural History"
            href: slides/rabo_03_unnatural_history.qmd
          - text: "Habitat"
            href: slides/rabo_04_habitat.qmd
          - text: "---"
          - text: "Ecology"
            href: TBA
          - text: "Climate & Phenology"
            href: TBA
          - text: "Survey Methods"
            href: slides/rabo_07_surveys.qmd
          - text: "Conservation"
            href: TBA
            
      - icon: github
        href: https://www.github.com/ryanpeek/rabo-workshop
  search: false
  page-footer: "written in Quarto by R. Peek"
execute: 
  freeze: auto
format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css
    link-external-newwindow: true
