project:
  type: website
  resources:
    - "data/*.csv"

website:
  title: "RABO Workshop"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - text: "Details"
        menu:
          - text: "Instructors"
            href: details/instructors.qmd
          - text: "Schedule"
            href: details/schedule.qmd
          - text: "Resources"
            href: details/resources.qmd
      - text: "Day 1"
        menu:
          - text: "Intro"
            href: slides/D1_rabo_00.qmd
          - text: "Natural History"
            href: slides/D1_rabo_01.qmd
          - text: "Status"
            href: slides/D1_rabo_02.qmd
          - text: "Habitat"
            href: slides/D1_rabo_03.qmd
            
            
      - icon: github
        href: https://www.github.com/ryanpeek/rabo-workshop
  search: false
  page-footer: "written in Quarto by R. Peek"

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css
