---
title: "Resources"
format:
  html:
    toc: true
    toc-expand: 3
    toc-title: Contents
    toc-location: right
    df-print: paged
bibliography: rabo_references.bib
csl: apa-6th-edition.csl
editor_options: 
  chunk_output_type: console
---


## Biblio

### A


 - Ashton, D.T. 2002. A Comparison of Abundance and Assemblage of Lotic Amphibians in Late-Seral and Second-Growth Redwood Forests in Humboldt County, California. Master’s Thesis, Humboldt State University, Arcata, CA.
 - Ashton, D.T., J.B. Bettaso, and H.H. Welsh, Jr. 2010. Foothill Yellow-legged Frog (*Rana boylii*) Distribution and Phenology Relative to Flow Management on the Trinity River. Oral presentation provided at the Trinity River Restoration Program's 2010 Trinity River Science Symposium 13 January 2010. http://www.trrp.net/library/document/?id=410
 - Ashton, D.T., A.J. Lind, and K.E. Schlick. 1997. Foothill Yellow-Legged Frog (*Rana boylii*) Natural History. USDA Forest Service, Pacific Southwest Research Station, Redwood Sciences Laboratory, Arcata, CA.
 - Ashton, D.T., and R.J. Nakamoto. 2007. *Rana boylii* (Foothill Yellow-legged Frog). Predation. Herpetological Review 38(4):442.

### B

 - Baird, S.F. 1854. Descriptions of New Genera and Species of North American Frogs. Proceedings of the Academy of Natural Sciences of Philadelphia 7:62.
 - Bar-Massada, A., V.C. Radeloff, and S.I. Stewart. 2014. Biotic and Abiotic Effects of Human Settlements in the Wildland–Urban Interface. BioScience 64(5):429–437.
 - Bauer S.D., J.L. Olson, A.C. Cockrill, M.G. van Hattem, L.M. Miller, M. Tauzer, and G. Leppig. 2015. Impacts of Surface Water Diversions for Marijuana-Cultivation on Aquatic Habitat in Four Northwestern California Watersheds. PLoS ONE 10(3):e0120016. https://doi.org/10.1371/journal.pone.0120016
 - Bee, M.A., and E.M. Swanson. 2007. Auditory Masking of Anuran Advertisement Calls by Road Traffic Noise. Animal Behaviour 74:1765-1776.
 - Beebee, T.J.C. 1995. Amphibian Breeding and Climate. Nature 374:219-220.
 - Behnke, R.J., and R.F. Raleigh. 1978. Grazing in the Riparian Zone: Impact and Management Perspectives. Pp. 184-189 In R.D. Johnson and J.F. McCormick (Technical Coordinators). Strategies for Protection and Management of Floodplain Wetlands and Other Riparian Ecosystems, U.S. Department of Agriculture, Forest Service, General Technical Report WO-12.
 - Belsky, A.J, A. Matzke, and S. Uselman. 1999. Survey of Livestock Influences on Stream and Riparian Ecosystems in the Western United States. Journal of Soil and Water Conservation 54(1):419-431.
 - Blaustein, A.R., D.G. Hokit, R.K. O'Hara and R.A. Holt. 1994. Pathogenic Fungus Contributes to Amphibian Losses in the Pacific Northwest. Biological Conservation 67(3):251-254.
 - Bobzien, S., and J.E. DiDonato. 2007. The Status of the California Tiger Salamander (*Ambystoma californiense*), California Red-Legged Frog (*Rana draytonii*), Foothill Yellow-Legged Frog (*Rana boylii*), and Other Aquatic Herpetofauna in the East Bay Regional Park District, California. Unpublished report. East Bay Regional Park District, Oakland, CA.
 - Bondi, C.A., S.M. Yarnell, and A.J. Lind. 2013. Transferability of Habitat Suitability Criteria for a Stream Breeding Frog (*Rana boylii*) in the Sierra Nevada, California. Herpetological Conservation and Biology 8(1):88-103.
 - Bourque, R.M. 2008. Spatial Ecology of an Inland Population of the Foothill Yellow-Legged Frog (*Rana boylii*) in Tehama County, California. Master’s Thesis, Humboldt State University, Arcata, CA.
 - Bourque, R.M., and J.B. Bettaso. 2011. *Rana boylii* (Foothill Yellow-legged Frogs). Reproduction. Herpetological Review 42(4):589. 
 - Brattstrom, B.H. 1962. Thermal Control of Aggregation Behavior in Tadpoles. Herpetologica 18(1):38-46.
 - Breedvelt, K.G.H., and M.J. Ellis. 2018. Foothill Yellow-legged Frog (*Rana boylii*) Growth, Longevity, and Population Dynamics from a 9-Year Photographic Capture-Recapture Study. Abstract of a paper presented at the CA/NV Amphibian and Reptile Task Force Annual Meeting 11-12 January 2018, Auburn, CA.
 - Brehme, C.S., S.A. Hathaway, and R.N. Fisher. 2018. An Objective Road Risk Assessment Method for Multiple Species: Ranking 166 Reptiles and Amphibians in California. Landscape Ecology 33:911-935. DOI: 10.1007/s10980-018-0640-1
 - Brode, J.M., and R.B. Bury. 1984. The Importance of Riparian Systems to Amphibians and Reptiles. Pp. 30-36 In R. E. Warner and K. M. Hendrix (Editors). Proceedings of the California Riparian Systems Conference, University of California, Davis.
 - Bursey, C.R., S.R. Goldberg, and J.B. Bettaso. 2010. Persistence and Stability of the Component Helminth Community of the Foothill Yellow-Legged Frog, *Rana boylii* (Ranidae), from Humboldt County, California, 1964–1965, Versus 2004–2007. The American Midland Naturalist 163(2):476-482. https://doi.org/10.1674/0003-0031-163.2.476
 - Burton, C.A., T.M. Hoefen, G.S. Plumlee, K.L. Baumberger, A.R. Backlin, E. Gallegos, and R.N. Fisher. 2016. Trace Elements in Stormflow, Ash, and Burned Soil Following the 2009 Station Fire in Southern California. PLoS ONE 11(5):e0153372. DOI: 10.1371/journal.pone.0153372
 - Bury, R.B. 1972. The Effects of Diesel Fuel on a Stream Fauna. California Department of Fish and Game Bulletin 58:291-295.
 - Bury, R.B., and N.R. Sisk. 1997. Amphibians and Reptiles of the Cow Creek Watershed in the BLM-Roseburg District. Draft report submitted to BLM-Roseburg District and Oregon Department of Fish and Wildlife-Roseburg. Biological Resources Division, USGS, Corvallis, OR. 
 - Butsic, V., and J.C. Brenner. 2016. Cannabis (Cannabis sativa or C. indica) Agriculture and the Environment: A Systematic, Spacially-explicit Survey and Potential Impacts. Environmental Research Letters 11(4):044023.

### C

 - California Department of Fish and Wildlife. 2019. A Status Review of the Foothill Yellow-legged Frog (*Rana boylii*) in California. California Department of Fish and Wildlife. https://nrm.dfg.ca.gov/FileHandler.ashx?DocumentID=174663&inline
 - California Department of Fish and Wildlife [CDFW]. 2018b. Green Diamond Resource Company Incidental Take Permit. California Endangered Species Act Incidental Take Permit No. 2081-2018-026-01. Northern Region, Eureka, CA.
 - California Department of Fish and Wildlife [CDFW]. 2018c. Humboldt Redwood Company Foothill Yellow-legged Frog Incidental Take Permit. California Endangered Species Act Incidental Take Permit No. 2081-2018-039-01. Northern Region, Eureka, CA.
 - California Department of Food and Agriculture [CDFA]. 2018. California Grape Acreage Report, 2017 Summary. https://www.nass.usda.gov/Statistics_by_State/California/Publications/Specialty_and_Other_Releases/Grapes/Acreage/2018/201804grpacSUMMARY.pdf
 - California Department of Forestry and Fire Protection [CAL FIRE]. 2019. Top 20 Largest California Wildfires. http://www.fire.ca.gov/communications/downloads/fact_sheets/Top20_Acres.pdf
 - California Department of Pesticide Regulation [CDPR]. 2018. The Top 100 Sites Used by Pounds of Active Ingredients Statewide in 2016 (All Pesticides Combined). https://www.cdpr.ca.gov/docs/pur/pur16rep/top_100_sites_lbs_2016.pdf
 - California Department of Water Resources [CDWR]. 2016. Drought and Water Year 2016: Hot and Dry Conditions Continue. 2016 California Drought Update.
 - California Natural Resources Agency [CNRA]. 2016. Safeguarding California: Implementation Action Plan. California Natural Resources Agency. http://resources.ca.gov/docs/climate/safeguarding/Safeguarding%20California-Implementation%20Action%20Plans.pdf
 - California Secretary of State [CSOS]. 2016. Proposition 64 Marijuana Legalization Initiative Statute, Analysis by the Legislative Analyst.
California Water Commission [CWC]. 2019. Proposition 1 Water Storage Investment Program: Funding the Public Benefits of Water Storage Projects. Website accessed April 5, 2019 at https://cwc.ca.gov/Water-Storage
 - Carah, J.K., J.K. Howard, S.E. Thompson, A.G. Short Gianotti, S.D. Bauer, S.M. Carlson, D.N. Dralle, M.W. Gabriel, L.L. Hulette, B.J. Johnson, C.A. Knight, S.J. Kupferberg, S.L. Martin, R.L. Naylor, and M.E. Power. 2015. High Time for Conservation: Adding the Environment to the Debate on Marijuana Liberalization. BioScience 65(8):822-829. DOI: 10.1093/biosci/biv083
 - Case, M.J., J.J. Lawler, and J.A. Tomasevic. 2015. Relative Sensitivity to Climate Change of Species in Northwestern North America. Biological Conservation 187:127-133.
 - Catenazzi, A., and S.J. Kupferberg. 2013. The Importance of Thermal Conditions to Recruitment Success in Stream-Breeding Frog Populations Distributed Across a Productivity Gradient. Biological Conservation 168:40-48. 
 - Catenazzi, A., and S.J. Kupferberg. 2017. Variation in Thermal Niche of a Declining River-breeding Frog: From Counter-Gradient Responses to Population Distribution Patterns. Freshwater Biology 62:1255-1265. 
 - Catenazzi, A., and S.J. Kupferberg. 2018. Consequences of Dam-Altered Thermal Regimes for a Riverine Herbivore’s Digestive Efficiency, Growth and Vulnerability to Predation. Freshwater Biology 63(9):1037-1048. DOI: 10.1111/fwb.13112
 - Cayan, D., M. Dettinger, I. Stewart, and N. Knowles. 2005. Recent Changes Towards Earlier Springs: Early Signs of Climate Warming in Western North America? Watershed Management Council Networker (Spring):3-7. 
 - Cayan, D.R., E.P. Maurer, M.D. Dettinger, M. Tyree, and K. Hayhoe. 2008. Climate Change Scenarios for the California Region. Climatic Change 87 (Supplement 1):21-42. DOI: 10.1007/s10584-007-9377-6
 - Climate Change Science Program [CCSP]. 2008. Weather and Climate Extremes in a Changing Climate, Regions of Focus: North America, Hawaii, Caribbean, and U.S. Pacific Islands. In T.R. Karl, G.A. Meehl, C.D. Miller, S.J. Hassol, A.M. Waple, and W.L. Murray (Editors). Department of Commerce, NOAA’s National Climate Data Center, Washington, DC. 
 - Conlon, J.M., A. Sonnevend, M. Patel, C. Davidson, P.F. Nielsen, T. Pál, and L.A. Rollins-Smith. 2003. Isolation of Peptides of the Brevinin-1 Family with Potent Candidacidal Activity from the Skin Secretions of the Frog *Rana boylii*. The Journal of Peptide Research 62:207-213.
 - Cook, B.I., T.R. Ault, and J.E. Smerdon. 2015. Unprecedented 21st Century Drought Risk in the American Southwest and Central Plains. Science Advances 1(1):e1400082. DOI: 10.1126/sciadv.1400082
 - Cook, D.G., S. White, and P. White. 2012. *Rana boylii* (Foothill Yellow-legged Frog) Upland Movement. Herpetological Review 43(2):325-326.
 - Cordone, A.J., and D.W. Kelley. 1961. The Influence of Inorganic Sediment on the Aquatic Life of Streams. California Fish and Game 47(2):189-228.
 - Crayon, J.J. 1998. *Rana catesbeiana* (Bullfrog). Diet. Herpetological Review 29(4):232.

### D
 - Davidson, C. 2004. Declining Downwind: Amphibian Population Declines in California and Historical Pesticide Use. Ecological Applications 14(6):1892-1902.
 - Davidson, C., H.B. Shaffer, and M.R. Jennings. 2002. Spatial Tests of the Pesticide Drift, Habitat Destruction, UV-B, and Climate-Change Hypotheses for California Amphibian Declines. Conservation Biology 16(6):1588-1601.
 - Davidson, C., M.F. Benard, H.B. Shaffer, J.M. Parker, C. O’Leary, J.M. Conlon, and L.A. Rollins-Smith. 2007. Effects of Chytrid and Carbaryl Exposure on Survival, Growth and Skin Peptide Defenses in Foothill Yellow-legged Frogs. Environmental Science and Technology 41(5):1771-1776. DOI: 10.1021/es0611947
 - Dawson, T.P., S.T. Jackson, J.I. House, I.C. Prentice, and G.M. Mace. 2011. Beyond Predictions: Biodiversity Conservation in a Changing Climate. Science 332:53-58.
 - Dettinger, M., H. Alpert, J. Battles, J. Kusel, H. Safford, D. Fougeres, C. Knight, L. Miller, and S. Sawyer. 2018. Sierra Nevada Summary Report. California’s Fourth Climate Change Assessment. Publication number: SUM-CCCA4-2018-004.
 - Dever, J.A. 2007. Fine-scale Genetic Structure in the Threatened Foothill Yellow-legged Frog (*Rana boylii*). Journal of Herpetology 41(1):168-173.
 - Dillingham, C.P., C.W. Koppl, J.E. Drennan, S.J. Kupferberg, A.J. Lind, C.S. Silver, T.V. Hopkins, K.D. Wiseman, and K.R. Marlow. 2018. In Situ Population Enhancement of an At-Risk Population of Foothill Yellow-legged Frogs, *Rana boylii*, in the North Fork Feather River, Butte County, California. Abstract of a paper presented at the CA/NV Amphibian and Reptile Task Force Annual Meeting 11-12 January 2018, Auburn, CA.
 - Doubledee, R.A., E.B. Muller, and R.M. Nisbet. 2003. Bullfrogs, Disturbance Regimes, and the Persistence of California Red-legged Frogs. Journal of Wildlife Management 67(2):424-438.
 - Drennan, J.E., K.A. Marlow, K.D. Wiseman, R.E. Jackman, I.A. Chan, and J.L. Lessard. 2015. *Rana boylii* Aging: A Growing Concern. Abstract of paper presented at the CA/NV Amphibian and Reptile Task Force Annual Meeting 8-10 January 2015, Malibu, CA.
 - Drost, C.A., and G.M. Fellers. 1996. Collapse of a Regional Frog Fauna in the Yosemite Area of the California Sierra Nevada, USA. Conservation Biology 10(2):414-425.

### E
 - East Contra Costa County Habitat Conservancy [ECCCHC]. 2018. East Contra Costa County Habitat Conservation Plan/Natural Community Conservation Plan Annual Report 2017.
 - Ecoclub Amphibian Group, K.L. Pope, G.M. Wengert, J.E. Foley, D.T. Ashton, and R.G. Botzler. 2016. Citizen Scientists Monitor a Deadly Fungus Threatening Amphibian Communities in Northern Coastal California, USA. Journal of Wildlife Diseases 52(3):516-523.
 - El Dorado Irrigation District [EID]. 2007. Project 184 Foothill Yellow-legged Frog Monitoring Plan.
 - Electric Consumers Protection Act [ECPA]. 1986. 16 United States Code § 797, 803.
 - Eriksson A., F. Elías-Wolff, B. Mehlig, and A. Manica. 2014. The Emergence of the Rescue Effect from Explicit Within- and Between-Patch Dynamics in a Metapopulation. Proceedings of the Royal Society B 281:20133127. http://dx.doi.org/10.1098/rspb.2013.3127
 - Evenden, F.G., Jr. 1948. Food Habitats of *Triturus granulosus* in Western Oregon. Copeia 1948(3):219-220.

### F
 - Fahrig, L., and G. Merriam. 1985. Habitat Patch Connectivity and Population Survival. Ecology 66(6):1762-1768.
 - Federal Energy Regulatory Commission [FERC]. 2007a. Order Issuing New License, Project No. 233-081.
 - Federal Energy Regulatory Commission [FERC]. 2007b. Relicensing Settlement Agreement for the Upper American River Project and Chili Bar Hydroelectric Project.
 - Federal Energy Regulatory Commission [FERC]. 2009a. Order Amending Forest Service 4(e) Condition 5A, Project No. 1962-187.
 - Federal Energy Regulatory Commission [FERC]. 2009b. Order Issuing New License, Project No. 2130-033.
 - Federal Energy Regulatory Commission [FERC]. 2014. Order Issuing New License, Project No. 2101-084.
 - Federal Energy Regulatory Commission [FERC]. 2018. Final Environmental Impact Statement. Lassen Lodge Hydroelectric Project. Project No. 12496-002.
 - Federal Energy Regulatory Commission [FERC]. 2019. Active Licenses. FERC eLibrary. Accessed March 10, 2019. https://www.ferc.gov/industries/hydropower/gen-info/licensing/active-licenses.xls
 - Fellers, G.M. 2005. Rana boylii Baird, 1854(b). Pp. 534-536 In M. Lannoo (Editor). Amphibian Declines: The Conservation Status of United States Species. University of California Press, Berkeley, CA.
 - Ferguson, E. 2019. Cultivating Cooperation: Pilot Study Around Headwaters of Mattole River Considers the Effect of Legal Cannabis Cultivators on Northern California Watersheds. Outdoor California 79(1):22-29.
 - Fidenci, P. 2006. *Rana boylii* (Foothill Yellow-legged Frog) Predation. Herpetological Review 37(2):208.
 - Field, C.B., G.C. Daily, F.W. Davis, S. Gaines, P.A. Matson, J. Melack, and N.L. Miller. 1999. Confronting Climate Change in California. Ecological Impacts on the Golden State. A report of the Union of Concerned Scientists, Cambridge, MA, and the Ecological Society of America, Washington, DC.
 - Fisher, R.N., and H.B. Shaffer. 1996. The Decline of Amphibians in California's Great Central Valley. Conservation Biology 10(5):1387-1397.
 - Fitch, H.S. 1936. Amphibians and Reptiles of the Rogue River Basin, Oregon. The American Midland Naturalist 17(3):634-652.
 - Fitch, H.S. 1938. *Rana boylii* in Oregon. Copeia 1938(3):148.
 - Fitch, H.S. 1941. The Feeding Habits of California Garter Snakes. California Fish and Game 27(2):1-32.
 - Florsheim, J.L., A. Chin, A.M. Kinoshita, and S. Nourbakhshbeidokhti. 2017. Effect of Storms During Drought on Post-Wildfire Recovery of Channel Sediment Dynamics and Habitat in the Southern California Chaparral, USA. Earth Surface Processes and Landforms 42(1):1482-1492. DOI: 10.1002/esp.4117.
 - Foe, C.G., and B. Croyle. 1998. Mercury Concentration and Loads from the Sacramento River and from Cache Creek to the Sacramento-San Joaquin Delta Estuary. Staff report, California Regional Water Quality Control Board, Central Valley Region, Sacramento, CA.
 - Fontenot, L.W., G.P. Noblet, and S.G. Platt. 1994. Rotenone Hazards to Amphibians and Reptiles. Herpetological Review 25(4):150-153, 156.
 - Fox, W. 1952. Notes on the Feeding Habits of Pacific Coast Garter Snakes. Herpetologica 8(1):4-8.
 - Fuller, D.D., and A.J. Lind. 1992. Implications of Fish Habitat Improvement Structures for Other Stream Vertebrates. Pp. 96-104 In Proceedings of the Symposium on Biodiversity of Northwestern California. R. Harris and D. Erman (Editors). Santa Rosa, CA. 
 - Fuller, T.E., K.L. Pope, D.T. Ashton, and H.H. Welsh. 2011. Linking the Distribution of an Invasive Amphibian (*Rana catesbeiana*) to Habitat Conditions in a Managed River System in Northern California. Restoration Ecology 19(201):204-213. DOI: 10.1111/j.1526-100X.2010.00708.x
 - Furey, P.C., S.J. Kupferberg, and A.J. Lind. 2014. The Perils of Unpalatable Periphyton: Didymosphenia and Other Mucilaginous Stalked Diatoms as Food for Tadpoles. Diatom Research 29(3):267-280.

### G
 - Gaos, A., and M. Bogan. 2001. A Direct Observation Survey of the Lower Rubicon River. California Department of Fish and Game, Rancho Cordova, CA.
 - Garcia and Associates [GANDA]. 2008. Identifying Microclimatic and Water Flow Triggers Associated with Breeding Activities of a Foothill Yellow‐Legged Frog (*Rana boylii*) Population on the North Fork Feather River, California. California Energy Commission, PIER Energy‐Related Environmental Research Program. CEC‐500‐2007‐041.
 - Garcia and Associates [GANDA]. 2017. 2016 Surveys for Foothill Yellow-legged Frog El Dorado County, California for the El Dorado Hydroelectric Project (FERC No. 184) – Job 642-9. Prepared for El Dorado Irrigation District, San Francisco, CA.
 - Garcia and Associates [GANDA]. 2018. Draft Results of 2017 Surveys for Foothill Yellow-legged Frog (*Rana boylii*) on the Cresta and Poe Reaches of the North Fork Feather River – Job 708/145. Prepared for Pacific Gas and Electric Company, San Francisco, CA.
 - Geisseler, D., and W.R. Horwath. 2016. Grapevine Production in California. A collaboration between the California Department of Food and Agriculture; Fertilization Education and Research, Project; and University of California, Davis. https://apps1.cdfa.ca.gov/FertilizerResearch/docs/Grapevine_Production_CA.pdf
 - Gibbs, J.P., and A.R. Breisch. 2001. Climate Warming and Calling Phenology of Frogs Near Ithaca, New York, 1900-1999. Conservation Biology 15(4):1175-1178.
 - Gomulkiewicz, R., and R.D. Holt. 1995.  When Does Evolution by Natural Selection Prevent Extinction? Evolution 49(1):201-207.
 - Gonsolin, T.T. 2010. Ecology of Foothill Yellow-legged Frogs in Upper Coyote Creek, Santa Clara County, CA. Master's Thesis. San Jose State University, San Jose, CA.
 - Grantham, T. E., A. M. Merenlender, and V. H. Resh. 2010. Climatic Influences and Anthropogenic Stressors: An Integrated Framework for Stream Flow Management in Mediterranean-climate California, U.S.A. Freshwater Biology 55 (Supplement 1):188-204. DOI: 10.1111/j.1365-2427.2009.02379.x
 - Green, D.M. 1986a. Systematics and Evolution of Western North American Frogs Allied to *Rana aurora* and *Rana boylii*: Karyological Evidence. Systematic Zoology 35(3):273-282.
 - Green, D.M. 1986b. Systematics and Evolution of Western North American Frogs Allied to *Rana aurora* and *Rana boylii*: Electrophoretic Evidence. Systematic Zoology 35(3):283-296.
 - Green Diamond Resource Company [GDRC]. 2018. Mad River Foothill Yellow-legged Frog Egg Mass Surveys Summary Humboldt County, California. Progress report to the California Department of Fish and Wildlife, Wildlife Branch-Nongame Wildlife Program, pursuant to the requirements of Scientific Collecting Permit Entity #6348.
 - Griffin, D., and K.J. Anchukaitis. 2014. How Unusual is the 2012-2014 California Drought? Geophysical Research Letters 41: 9017-9023. DOI: 10.1002/2014GL062433.
 - Grinnell, J., and T. I. Storer. 1924. Animal Life in the Yosemite: An Account of the Mammals, Birds, Reptiles, and Amphibians in a Cross-section of the Sierra Nevada. University of California Press, Berkeley, CA.
 - Grinnell, J., J. Dixon, and J.M. Linsdale. 1930. Vertebrate Natural History of a Section of Northern California Through the Lassen Peak Region. University of California Press, Berkeley, CA. 

### H
 - Haggarty, M. 2006. Habitat Differentiation and Resource Use Among Different Age Classes of Post Metamorphic Rana boylii on Red Bank Creek, Tehama County, California. Master’s Thesis. Humboldt State University, Arcata, CA.
 - Harvey, B.C., and T.E. Lisle. 1998. Effects of Suction Dredging on Streams: A Review and an Evaluation Strategy. Fisheries 23(8):8-17.
 - Hayes, M.P., and M.R. Jennings. 1986. Decline of Ranid Frog Species in Western North America: Are Bullfrogs (*Rana catesbeiana*) Responsible? Journal of Herpetology 20(4):490-509.
 - Hayes, M.P., and M.R. Jennings. 1988. Habitat Correlates of Distribution of the California Red-legged Frog (*Rana aurora draytonii*) and the Foothill Yellow-Legged Frog (*Rana boylii*): Implications for Management. Pp. 144-158 In Management of Amphibians, Reptiles, and Small Mammals in North America, General Technical Report. RM-166 R.C. Szaro, K.E. Severson, and D.R. Patton (Technical Coordinators). USDA Forest Service, Rocky Mountain Forest and Range Experiment Station, Fort Collins, CO.
 - Hayes, M.P., C.A. Wheeler, A.J. Lind, G.A. Green, and D.C. Macfarlane (Technical Coordinators). 2016. Foothill Yellow-Legged Frog Conservation Assessment in California. Gen. Tech. Rep. PSW-GTR-248. U.S. Department of Agriculture, Forest Service, Pacific Southwest Research Station, Albany, CA.
 - Hayes, T., K. Haston, M. Tsui, A. Hoang, C. Haeffle, and A. Vonk. 2003. Atrazine-induced Hermaphroditism at 0.1 ppb in American Leopard Frogs (*Rana pipiens*): Laboratory and Field Evidence. Environmental Health Perspectives 11(4):568-575.
 - Hayes, T.B., P. Case, S. Chui, D. Chung, C. Haeffele, K. Haston, M. Lee, V. P. Mai, Y. Marjuoa, J. Parker, and M. Tsui. 2006. Pesticide Mixtures, Endocrine Disruption, and Amphibian Declines: Are We Underestimating the Impact? Environmental Health Perspectives 114(Supplement 1):40-50.
 - Hemphill, D.V. 1952. The Vertebrate Fauna of the Boreal Areas of the Southern Yolla Bolly Mountains, California. PhD Dissertation. Oregon State University, Corvallis.
 - Hillis, D.M., and T.P. Wilcox. 2005. Phylogeny of the New World true frogs (Rana). Molecular Phylogenetics and Evolution 34:299-314.
 - Hoffmann, A.A., and C.M. Sgrò. 2011. Climate Change and Evolutionary Adaptation. Nature 470:479-485. https://www.nature.com/articles/nature09670
 - Hogan, S., and C. Zuber. 2012. North Fork American River 2012 Summary Report. California Department of Fish and Wildlife Heritage and Wild Trout Program, Rancho Cordova, CA.
 - Hopkins, G.R., S.S. French, and E.D. Brodie. 2013. Increased Frequency and Severity of Developmental Deformities in Rough-skinned Newt (*Taricha granulosa*) Embryos Exposed to Road Deicing Salts (NaCl & MgCl2). Environmental Pollution 173:264-269. http://dx.doi.org/10.1016/j.envpol.2012.10.002
 - Hothem, R.L., A.M. Meckstroth, K.E. Wegner, M.R. Jennings, and J.J. Crayon. 2009. Diets of Three Species of Anurans from the Cache Creek Watershed, California, USA. Journal of Herpetology 43(2):275-283.
 - Hothem, R.L., M.R. Jennings, and J.J. Crayon. 2010. Mercury Contamination in Three Species of Anuran Amphibians from the Cache Creek Watershed, California, USA. Environmental Monitoring and Assessment 163:433-448. https://doi.org/10.1007/s10661-009-0847-3
 - Humboldt Redwoods Company [HRC]. 2015. Habitat Conservation Plan for the Properties of The Pacific Lumber Company, Scotia Pacific Holding Company, and Salmon Creek Corporation under the Ownership and Management of Humboldt Redwood Company, LLC, as of July 2008. Established February 1999, Revised 12 August 2015.
ICF International. 2012. Final Santa Clara Valley Habitat Plan. https://scv-habitatagency.org/178/Santa-Clara-Valley-Habitat-Plan

### J
 - Jackman, R.E., J.E. Drennan, K.R. Marlow, and K.D. Wiseman. 2004. Some Effects of Spring and Summer Pulse Flows on River-breeding Foothill Yellow-legged Frogs (*Rana boylii*) along the North Fork Feather River. Abstract of paper presented at the Cal-Neva and Humboldt Chapters of the American Fisheries Society Annual Meeting 23 April 2004, Redding, CA.
 - Jennings, M.R., and M.P. Hayes. 1985. Pre-1900 Overharvest of California Red-Legged Frogs (*Rana aurora draytonii*): The Inducement for Bullfrog (*Rana catesbeiana*) Introduction. Herpetologica 41(1):94-103. 
 - Jennings, M.R., and M.P. Hayes. 1994. Amphibian and Reptile Species of Special Concern in California. Contract No. 8023. Final Report submitted to the California Department of Fish and Game, Inland Fisheries Division, Rancho Cordova, CA. 
Jennings, M.R., and M.P. Hayes. 2005. *Rana boylii* (Foothill Yellow-legged Frog). Coloration. Herpetological Review 36(4):438.
 - Jones & Stokes Associates. 2006. East Contra Costa County Habitat Conservation Plan/Natural Communities Conservation Plan.

### K
 - Karraker, N.E., J.P. Gibbs, and J.R. Vonesh. 2008. Impacts of Road Deicing Salt on the Demography of Vernal Pool-breeding Amphibians. Ecological Applications 18(3):724-734.
 - Kats, L.B., and R.P. Ferrer. 2003. Alien Predators and Amphibian Declines: Review of Two Decades of Science and the Transition to Conservation. Diversity and Distributions 9(2):99-110.
 - Kauffman, J.B., and W.C. Krueger. 1984. Livestock Impacts on Riparian Ecosystems and Streambank Management Implications…A review. Journal of Range Management 37(5):430-437.
 - Kauffman, J.B., W.C. Krueger, and M. Varva. 1983. Impacts of Cattle on Streambanks in Northeastern Oregon. Journal of Range Management 36(6):683-685.
Keeley, J.E. 2005. Fire History of the San Francisco East Bay Region and Implications for Landscape Patterns. International Journal of Wildland Fire 14:285-296.
 - Keeley, J.E., and A.D. Syphard. 2016. Climate Change and Future Fire Regimes: Examples from California. Geosciences 6(7):37. DOI: 10.3390/geosciences6030037
 - Kerby, J.L., and A. Sih. 2015. Effects of Carbaryl on Species Interactions of the Foothill Yellow Legged Frog (*Rana boylii*) and the Pacific Treefrog (*Pseudacris regilla*). Hydrobiologia 746(1):255-269. DOI: 10.1007/s10750-014-2137-5
 - Kiesecker, J.M. 2002. Synergism Between Trematode Infection and Pesticide Exposure: A Link to Amphibian Limb Deformities in Nature? PNAS 99(15):9900-9904. https://doi.org/10.1073/pnas.152098899
 - Kiesecker, J.M., and A.R. Blaustein. 1997. Influences of Egg Laying Behavior on Pathogenic Infection of Amphibian Eggs. Conservation Biology 11(1):214-220.
 - Knowles, N., M.D. Dettinger, and D.R. Cayan. 2006. Trends in Snowfall Versus Rainfall in the Western United States. Journal of Climate 19(18):4545-4559. https://doi.org/10.1175/JCLI3850.1
 - Kupferberg, S.J. 1996a. Hydrologic and Geomorphic Factors Affecting Conservation of a River-Breeding Frog (*Rana boylii*). Ecological Applications 6(4):1322-1344.
 - Kupferberg, S.J. 1996b. The Ecology of Native Tadpoles (*Rana boylii* and *Hyla regilla*) and the Impact of Invading Bullfrogs (Rana catesbeiana) in a Northern California River. PhD Dissertation. University of California, Berkeley.
 - Kupferberg, S.J. 1997a. Bullfrog (*Rana catesbeiana*) Invasion of a California River: The Role of Larval Competition. Ecology 78(6):1736-1751. 
 - Kupferberg, S.J. 1997b. The Role of Larval Diet in Anuran Metamorphosis. American Zoology 37:146-159.
 - Kupferberg, S., and A. Catenazzi. 2019. Between Bedrock and a Hard Place: Riverine Frogs Navigate Tradeoffs of Pool Permanency and Disease Risk During Drought. Abstract prepared for the Joint Meeting of Ichthyologists and Herpetologists. 24-28 July 2019, Snowbird, UT.
 - Kupferberg, S.J., A. Catenazzi, K. Lunde, A. Lind, and W. Palen. 2009a. Parasitic Copepod (*Lernaea cyprinacea*) Outbreaks in Foothill Yellow-legged Frogs (*Rana boylii*) Linked to Unusually Warm Summers and Amphibian Malformations in Northern California. Copeia 2009(3):529-537. 
 - Kupferberg, S.J., A. Catenazzi, and M.E. Power. 2011a. The Importance of Water Temperature and Algal Assemblage for Frog Conservation in Northern California Rivers with Hydroelectric Projects. Final Report to the California Energy Commission, PIER. CEC-500-2014-033.
 - Kupferberg, S.J., and P.C. Furey. 2015. An Independent Impact Analysis using Carnegie State Vehicular Recreation Area Habitat Monitoring System Data. Friends of Tesla Park Technical Memorandum. DOI: 10.13140/RG.2.1.4898.9207
 - Kupferberg, S.J., A. Lind, J. Mount, and S. Yarnell. 2009b. Pulsed Flow Effects on the Foothill Yellow-Legged Frog (*Rana boylii*): Integration of Empirical, Experimental, and Hydrodynamic Modeling Approaches. Final Report. California Energy Commission, PIER. CEC-500-2009-002. 
 - Kupferberg, S.J, A.J. Lind, and W.J. Palen. 2009c. Pulsed Flow Effects on the Foothill Yellow-legged Frog (*Rana boylii*): Population Modeling. Final Report to the California Energy Commission, PIER. CEC-500-2009-002a.
 - Kupferberg, S.J., A.J. Lind, V. Thill, and S.M. Yarnell. 2011b. Water Velocity Tolerance in Tadpoles of the Foothill Yellow-legged Frog (*Rana boylii*): Swimming Performance, Growth, and Survival. Copeia 2011(1):141-152. 
 - Kupferberg, S.J., W.J. Palen, A.J. Lind, S. Bobzien, A. Catenazzi, J. Drennan, and M.E. Power. 2012. Effects of Flow Regimes Altered by Dams on Survival, Population Declines, and Range-wide Losses of California River-Breeding Frogs. Conservation Biology 26(3):513-524.

### L
 - Lambert, M.R., T. Tran, A. Kilian, T. Ezaz, and D.K. Skelly. 2019. Molecular Evidence for Sex Reversal in Wild populations of Green Frogs (*Rana clamitans*). PeerJ 7:e6449. DOI: 10.7717/peerj.6449
 - Lande, R., and S. Shannon. 1996. The Role of Genetic Variation in Adaptation and Population Persistence in a Changing Environment. Evolution 50(1):434-437.
 - Leidy, R.A., E. Gonsolin, and G.A. Leidy. 2009. Late-summer Aggregation of the Foothill Yellow-legged Frog (*Rana boylii*) in Central California. The Southwestern Naturalist 54(3):367-368.
 - LeNoir, J.S., L.L. McConnell, G.M. Fellers, T.M. Cahill, and J.N. Seiber. 1999. Summertime Transport of Current-Use Pesticides from California’s Central Valley to the Sierra Nevada Mountain Range, USA. Environmental Toxicology and Chemistry 18(12):2715-2722.
 - Lind, A.J. 2005. Reintroduction of a Declining Amphibian: Determining an Ecologically Feasible Approach for the Foothill Yellow-legged Frog (*Rana boylii*) Through Analysis of Decline Factors, Genetic Structure, and Habitat Associations. PhD Dissertation. University of California, Davis.
 - Lind, A.J., J.B. Bettaso, and S.M. Yarnell. 2003a. Natural History Notes: *Rana boylii* (Foothill Yellow-legged Frog) and *Rana catesbeiana* (Bullfrog). Reproductive behavior. Herpetological Review 34(3):234-235.
 - Lind, A.J., L. Conway, H. (Eddinger) Sanders, P. Strand, and T. Tharalson. 2003b. Distribution, Relative Abundance, and Habitat of Foothill Yellow-legged Frogs (*Rana boylii*) on National Forests in the Southern Sierra Nevada Mountains of California. Report to the FHR Program of Region 5 of the USDA Forest Service.
 - Lind, A.J., P.Q. Spinks, G.M. Fellers, and H.B. Shaffer. 2011. Rangewide Phylogeography and Landscape Genetics of the Western U.S. Endemic Frog *Rana boylii* (Ranidae): Implications for the Conservation of Frogs and Rivers. Conservation Genetics 12:269-284.
 - Lind, A.J., and H.H. Welsh, Jr. 1994. Ontogenetic Changes in Foraging Behaviour and Habitat Use by the Oregon Garter Snake, *Thamnophis atratus hydrophilus*. Animal Behaviour 48:1261-1273.
 - Lind, A.J., H.H. Welsh, Jr., and C.A. Wheeler. 2016. Foothill Yellow-legged Frog (*Rana boylii*) Oviposition Site Choice at Multiple Spatial Scales. Journal of Herpetology 50(2):263-270.
 - Lind, A.J., H.H. Welsh, Jr., and R.A. Wilson. 1996. The Effects of a Dam on Breeding Habitat and Egg Survival of the Foothill Yellow-Legged Frog (*Rana boylii*) in Northwestern California. Herpetological Review 27(2):62-67.
 - Little, E.E., and R.D. Calfee. 2000. The Effects of UVB Radiation on the Toxicity of Fire-Fighting Chemicals. Final Report. U.S. Geological Service, Columbia Environmental Research Center, Columbia, MO.
 - Loomis, R.B. 1965. The Yellow-legged Frog, *Rana boylei*, from the Sierra San Pedro Mártir, Baja California Norte, México. Herpetologica 21(1):78-80.
 - Lowe, J. 2009. Amphibian Chytrid (*Batrachochytrium dendrobatidis*) in Postmetamorphic *Rana boylii* in Inner Coast Ranges of Central California. Herpetological Review 40(2):180.

### M
 - Macey, R.J., J.L. Strasburg, J.A. Brisson, V.T. Vredenburg, M. Jennings, and A. Larson. 2001. Molecular Phylogenetics of Western North American Frogs of the *Rana boylii* Species Group. Molecular Phylogenetics and Evolution 19(1):131-143.
 - MacTague, L., and P.T. Northen. 1993. Underwater Vocalization by the Foothill Yellow-Legged Frog (*Rana boylii*). Transactions of the Western Section of the Wildlife Society 29:1-7.
 - Mallakpour, I., M. Sadegh, and A. AghaKouchak. 2018. A New Normal for Streamflow in California in a Warming Climate: Wetter Wet Seasons and Drier Dry Seasons. Journal of Hydrology 567:203-211.
 - Mallery, M. 2010. Marijuana National Forest: Encroachment on California Public Lands for Cannabis Cultivation. Berkeley Undergrad Journal 23(2):1-50. http://escholarship.org/uc/item/7r10t66s#page-2
 - Marlow, C.B., and T.M. Pogacnik. 1985. Time of Grazing and Cattle-Induced Damage to Streambanks. Pp. 279-284 In R.R. 
 - Johnson, C.D. Ziebell, D.R. Patton, P.F. Folliott, and R.H. Hamre (Technical Coordinators). Riparian Ecosystems and Their Management: Reconciling Conflicting Uses. U.S. Department of Agriculture, Forest Service, General Technical Report RM-120.
 - Marlow, K.R., K.D. Wiseman, C.A. Wheeler, J.E. Drennan, and R.E. Jackman. 2016. Identification of Individual Foothill Yellow-legged Frogs (*Rana boylii*) using Chin Pattern Photographs: A Non-Invasive and Effective Method for Small Population Studies. Herpetological Review 47(2):193-198.
 - Martin, C. 1940. A New Snake and Two Frogs for Yosemite National Park. Yosemite Nature Notes 19(11):83-85.
 - Martin, P.L., R.E. Goodhue, and B.D. Wright. 2018. Introduction. Pp. 1-25 In California Agriculture: Dimensions and Issues. P.L. Martin, R.E. Goodhue, and B.D. Wright (Editors). Giannini Foundation Information Series 18-01, University of California. https://s.giannini.ucop.edu/uploads/giannini_public/07/5c/075c8120-3705-4a79-ae74-130fdfe46c6b/introduction.pdf
 - McCartney-Melstad, E., M. Gidiş, and H.B. Shaffer. 2018. Population Genomic Data Reveal Extreme Geographic Subdivision and Novel Conservation Actions for the Declining Foothill Yellow-legged Frog. Heredity 121:112-125. 
 - Megahan, W.F., J.G. King, and K.A. Seyedbagheri. 1995. Hydrologic and Erosional Responses of a Granitic Watershed to Helicopter Logging and Broadcast Burning. Forest Science 41(4):777-795.
 - Merenlender, A.M. 2000. Mapping Vineyard Expansion Provides Information on Agriculture and the Environment. California Agriculture 54(3):7-12.
 - Mierau, D.W., W.J. Trush, G.J. Rossi, J.K. Carah, M.O. Clifford, and J.K. Howard. 2017. Managing Diversions in Unregulated Streams using a Modified Percent-of-Flow Approach. Freshwater Biology 63:752-768. DOI: 10.1111/fwb.12985
 - Moyle, P.B. 1973. Effects of Introduced Bullfrogs, Rana catesbeiana, on the Native Frogs of the San Joaquin Valley, California. Copeia 1973(1):18-22.
 - Moyle, P.B., and P.J. Randall. 1998. Evaluating the Biotic Integrity of Watersheds in the Sierra Nevada, California. Conservation Biology 12(6):1318-1326.
Napa County. 2010. Napa County Voluntary Oak Woodlands Management Plan. 

### N
 - National Integrated Drought Information System [NIDIS]. 2019. Drought in California from 2000-2019. National Drought Mitigation Center, U.S. Department of Agriculture Federal Drought Assistance. Accessed 25 April 2019 at https://www.drought.gov/drought/states/california
 - National Marine Fisheries Service [NMFS]. 2012. Southern California Steelhead Recovery Plan. Southwest Region, Protected Resources Division, Long Beach, CA. 
 - National Marine Fisheries Service [NMFS]. 2013. South-Central California Coast Steelhead Recovery Plan. West Coast Region, California Coastal Area Office, Long Beach, CA.
 - National Marine Fisheries Service [NMFS]. 2014. Recovery Plan for the Evolutionarily Significant Units of Sacramento River Winter-run Chinook Salmon and Central Valley Spring-run Chinook Salmon and the Distinct Population Segment of California Central Valley Steelhead. California Central Valley Area Office, Sacramento, CA.
 - National Marine Fisheries Service [NMFS]. 2016. Coastal Multispecies Recovery Plan. National Marine Fisheries Service, West Coast Region, Santa Rosa, CA.
 - Nussbaum, R.A., E.D. Brodie, Jr., and R.M. Storm. 1983. Amphibians & Reptiles of the Pacific Northwest. University Press of Idaho, Moscow, ID.
 
### O
 - Off-Highway Motor Vehicle Recreation Commission [OHMVRC]. 2017. Off-Highway Motor Vehicle Recreation Commission Program Report, January 2017. http://ohv.parks.ca.gov/pages/1140/files/OHMVR-Commission-2017-Program_Report-FINAL-Mar2017_web.pdf
 - Office of Environmental Health Hazard Assessment [OEHAA], California Environmental Protection Agency. 2018. Indicators of Climate Change in California. https://oehha.ca.gov/media/downloads/climate-change/report/2018caindicatorsreportmay2018.pdf
 - Olson, D.H., and R. Davis. 2009. Conservation Assessment for the Foothill Yellow-legged Frog (*Rana boylii*) in Oregon. USDA Forest Service Region 6 and USDI Bureau of Land Management Interagency Special Status Species Program.
 - Olson, E.O., J.D. Shedd, and T.N. Engstrom. 2016. A Field Inventory and Collections Summary of Herpetofauna from the Sutter Buttes, an “Inland Island” within California’s Great Central Valley. Western North American Naturalist 76(3):352-366.
 
### P
 - Pacific Gas and Electric [PG&E]. 2018. Pit 3, 4, and 5 Hydroelectric Project (FERC Project No. 233) Foothill Yellow-Legged Frog Monitoring 2017 Annual Report.
 - Padgett-Flohr, G.E., and R.L. Hopkins. 2009. *Batrachochytrium dendrobatidis*, a Novel Pathogen Approaching Endemism in Central California. Diseases of Aquatic Organisms 83:1-9.
 - Palstra, F.P., and D.E. Ruzzante. 2008. Genetic Estimates of Contemporary Effective Population Size: What Can They Tell Us about the Importance of Genetic Stochasticity for Wild Population Persistence? Molecular Ecology 17:3428-3447. DOI: 10.1111/j.1365-294X.2008.03842.x
 - Paoletti, D.J., D.H. Olson, and A.R. Blaustein. 2011. Responses of Foothill Yellow-legged Frog (*Rana boylii*) Larvae to an Introduced Predator. Copeia 2011(1):161-168.
 - Parks, S.A., C. Miller, J.T. Abatzoglou, L.M. Holsinger, M-A. Parisien, and S.Z. Dobrowski. 2016. How Will Climate Change Affect Wildland Fire Severity in the Western US? Environmental Research Letters 11:035002. DOI: 10.1088/1748-9326/11/3/035002
 - Parmesan, C., and G. Yohe. 2003. A Globally Coherent Fingerprint of Climate Change Impacts across Natural Systems. Nature 421(6918):37-42. DOI: 10.1038/nature01286
 - Parris, K.M., M. Velik-Lord, and J.M.A. North. 2009. Frogs Call at a Higher Pitch in Traffic Noise. Ecology and Society 12(1):25. http://www.ecologyandsociety.org/vol14/iss1/art25/
 - Peek, R. 2010. Landscape Genetics of Foothill Yellow-Legged Frogs (*Rana boylii*) in regulated and unregulated rivers: Assessing connectivity and genetic fragmentation. Master of Science (MS), University of San Francisco.
 - Peek, R.A. 2018. Population Genetics of a Sentinel Stream-breeding Frog (*Rana boylii*). PhD Dissertation. University of California, Davis.
 - Peek, R. A., M. Bedwell, S. M. O’Rourke, C. Goldberg, G. M. Wengert, and M. R. Miller. 2019. Hybridization between two parapatric ranid frog species in the northern Sierra Nevada, California, USA. Molecular Ecology 28:4636–4647.
  - Peek, R., and S. Kupferberg. 2016. Assessing the Need for Endangered Species Act Protection of the Foothill Yellow-legged Frog (*Rana boylii*): What do Breeding Censuses Indicate? Abstract of poster presented at the CA/NV Amphibian and Reptile Task Force Annual Meeting 7-8 January 2016, Davis, CA.
  - Peek, R. A., S. M. O’Rourke, and M. R. Miller. 2021. Flow modification associated with reduced genetic health of a river‐breeding frog, *Rana boylii*. Ecosphere 12.
 - Pilliod, D.S., R.B. Bury, E.J. Hyde, C.A. Pearl, and P.S. Corn. 2003. Fire and Amphibians in North America. Forest Ecology and Management 178:163-181. 
 - Placer County Water Agency [PCWA]. 2008. Final AQ 12 – Special-Status Amphibian and Aquatic Reptile Technical Study Report – 2007. Placer County Water Agency Middle Fork American River Project (FERC No. 2079), Auburn, CA.
 - Pounds, A., A.C.O.Q. Carnaval, and S. Corn. 2007. Climate Change, Biodiversity Loss, and Amphibian Declines. Pp. 19-20 In C. Gascon, J.P. Collins, R.D. Moore, D.R. Church, J.E. McKay, and J.R. Mendelson III (Editors). IUCN Amphibian Conservation Action Plan, Proceedings: IUCN/SSC Amphibian Conservation Summit 2005.
 - Powell, R., R. Conant, and J.T. Collins. 2016. Peterson Field Guide to Reptiles and Amphibians of Eastern and Central America, Fourth Edition. 
 - Power, M.E., M.S. Parker, and W.E. Dietrich. 2008. Seasonal Reassembly of a River Food Web: Floods, Droughts, and Impacts of Fish. Ecological Monographs 78(2):263-282.
 - Prado, M. 2005. Rare Frogs Put at Risk by Visitors in West Marin. Marin Independent Journal. Newspaper article, May 09, 2005.
 - Public Policy Institute of California [PPIC]. 2018. Storing Water. https://www.ppic.org/publication/californias-water-storing-water/
 - Public Policy Institute of California [PPIC]. 2019. California’s Future: Population. https://www.ppic.org/wp-content/uploads/californias-future-population-january-2019.pdf

### R
 - Radeloff, V.C., D.P. Helmers, H.A. Kramer, M.H. Mockrin, P.M. Alexandre, A. Bar-Massada, V. Butsic, T.J. Hawbaker, S. Martinuzzi, A.D. Syphard, and S.I. Stewart. 2018. Rapid Growth of the US Wildland-Urban Interface Raises Wildfire Risk. PNAS 115(13):3314-3319. https://doi.org/10.1073/pnas.1718850115
 - Railsback, S.F., B.C. Harvey, S.J. Kupferberg, M.M. Lang, S. McBain, and H.H. Welsh, Jr. 2016. Modeling Potential River Management Conflicts between Frogs and Salmonids. Canadian Journal of Fisheries and Aquatic Sciences 73:773-784.
 - Reeder, N.M.M., A.P. Pessier, and V.T. Vredenburg. 2012. A Reservoir Species for the Emerging Amphibian Pathogen *Batrachochytrium dendrobatidis* Thrives in a Landscape Decimated by Disease. PLoS ONE 7(3):e33567. https://doi.org/10.1371/journal.pone.0033567
 - Riegel, J.A. 1959. The Systematics and Distribution of Crayfishes in California. California Fish and Game 45:29-50.
 - Relyea, R.A. 2005. The Impact of Insecticides and Herbicides on the Biodiversity and Productivity of Aquatic Communities. Ecological Applications 15(2):618-627.
 - Relyea, R.A., and N. Diecks. 2008. An Unforeseen Chain of Events: Lethal Effects of Pesticides on Frogs at Sublethal Concentrations. Ecological Applications 18(7):1728-1742.
 - Rombough, C. 2006. Winter Habitat Use by Juvenile Foothill Yellow-legged Frogs (*Rana boylii*): The Importance of Seeps. In Abstracts from the 2006 Annual Meetings of the Society for Northwestern Vertebrate Biology and the Washington Chapter of the Wildlife Society. Northwest Naturalist 87(2):159.
 - Rombough, C.J., J. Chastain, A.M. Schwab, and M.P. Hayes. 2005. *Rana boylii* (Foothill Yellow-legged Frog). Predation. Herpetological Review 36(4):438-439.
 - Rombough, C.J., and M.P. Hayes. 2005. *Rana boylii* (Foothill Yellow-legged Frog). Predation: Eggs and Hatchlings. Herpetological Review 36(2):163-164.
 - Rombough, C.J., and M.P. Hayes. 2007. *Rana boylii* (Foothill Yellow-legged Frog). Reproduction. Herpetological Review 38(1):70-71.
 - Russell, K.R., D.H. Van Lear, and D.C. Guynn, Jr. 1999. Prescribed Fire Effects on Herpetofauna: Review and Management Implications. Wildlife Society Bulletin 27(2):374-384.

### S
 - San Joaquin Council of Governments, Inc. [SJCOG 2018]. San Joaquin County Multi-Species Habitat Conservation and Open Space Plan 2018 Annual Report.
 - San Joaquin County. 2000. San Joaquin County Multi-Species Habitat Conservation Plan and Open Space Plan.
 - Santa Clara Valley Habitat Agency [SCVHA]. 2019. Santa Clara Valley Habitat Plan 4th Annual Report FY2017-2018.
 - Scheele, B.C., F. Pasmans, L.F. Skerratt, L. Berger, A. Martel, W. Beukema, A.A. Acevedo, P.A. Burrows, T. Carvalhos, A. Catenazzi, I. De la Riva, M.C. Fisher, S.V. Flechas, C.N. Foster, P. Frías-Álvarez, T.W.J. Garner, B. Gratwicke, J.M. Guayasamin, M. Hirschfeld, J.E. Kolby, T.A. Kosch, E. La Marca, D.B. Lindenmayer, K.R. Lips, A.V. Longo, R. Maneyro, C.A. McDonald, J. Mendelson III, P. Palacios-Rodriguez, G. Parra-Olea, C.L. Richards-Zawacki, M-O. Rödel, S.M. Rovito, C. Soto-Azat, L.F. Toledo, J. Voyles, C. Weldon, S.M. Whitfield, M. Wilkinson, K.R. Zamudio, and S. Canessa. 2019. Amphibian Fungal Panzootic Causes Catastrophic and Ongoing Loss of Biodiversity. Science 363(6434):1459-1463. DOI: 10.1126/science.aav0379
 - Siekert, R.E., Q.D. Skinner, M.A. Smith, J.L. Dodd, and J.D. Rogers. 1985. Channel Response of an Ephemeral Stream in Wyoming to Selected Grazing Treatments. Pp. 276-278 In R.R. Johnson, C.D. Ziebell, D.R. Patton, P.F. Folliott, and R.H. Hamre (Technical Coordinators). Riparian Ecosystems and Their Management: Reconciling Conflicting Uses. U.S. Department of Agriculture, Forest Service, General Technical Report RM-120.
 - Silver, C.S. 2017. Population-level Variation in Vocalizations of *Rana boylii*, the Foothill Yellow-legged Frog. Master’s Thesis. California State University, Chico, Chico, CA.
 - Snover, M.L., and M.J. Adams. 2016. Herpetological Monitoring and Assessment on the Trinity River, Trinity County, California-Final Report: U.S. Geological Survey Open-File Report 2016-1089. http://dx.doi.org/10.3133/ofr20161089
 - Sparling, D.W., and G.M. Fellers. 2007. Comparative Toxicity of Chlorpyrifos, Diazinon, Malathion and Their Oxon Derivatives to *Rana boylii*. Environmental Pollution 147:535-539.
 - Sparling, D.W., and G.M. Fellers. 2009. Toxicity of Two Insecticides to California, USA, Anurans and Its Relevance to Declining Amphibian Populations. Environmental Toxicology and Chemistry 28(8):1696-1703.
 - Sparling, D.W., G.M. Fellers, and L.L. McConnell. 2001. Pesticides and Amphibian Declines in California, USA. Environmental Toxicology and Chemistry 20(7):1591-1595.
 - Spencer, C.N., and F.R. Hauer. 1991. Phosphorus and Nitrogen Dynamics in Streams During a Wildfire. Journal of the North American Benthological Society 10(1):24-30.
 - Spring Rivers Ecological Sciences. 2003. Foothill Yellow-legged Frog (*Rana boylii*) Studies in 2002 for Pacific Gas and Electric Company’s Pit 3, 4, and 5 Hydroelectric Project (FERC No. 233). Pacific Gas and Electric Company, Technical and Ecological Services, San Ramon, CA.
 - State Board of Forestry and Fire Protection [SBFFP]. 2018. 2018 Strategic Fire Plan for California. Accessed March 1, 2019 at: http://cdfdata.fire.ca.gov/pub/fireplan/fpupload/fpppdf1614.pdf
 - State Water Resources Control Board [SWRCB]. 2017. Water Quality Certification for the Pacific Gas and Electric Company Poe Hydroelectric Project, Federal Energy Regulatory Commission Project No. 2107. 
 - State Water Resources Control Board [SWRCB]. 2018. Water Quality Certification for the South Feather Water and Power Agency South Feather Power Project, Federal Energy Regulatory Commission Project No. 2088. 
 - State Water Resources Control Board [SWRCB]. 2019. February 2019 Executive Director’s Report. Accessed February 18, 2019 at: https://www.waterboards.ca.gov/board_info/exec_dir_rpts/2019/ed_rpt_021119.pdf
 - Stebbins, R.C. 2003. Peterson Filed Guides Western Reptiles and Amphibians. Third Edition. Houghton Mifflin Company, Boston, MA. 
 - Stebbins, R.C., and S.M. McGinnis. 2012. Field Guide to Amphibians and Reptiles of California. Revised Edition. University of California Press, Berkeley, CA. 
 - Stephens, S.L., N. Burrows, A. Buyantuyev, R.W. Gray, R.E. Keane, R. Kubian, S. Liu, F. Seijo, L. Shu, K.G. Tolhurst, and J.W. van Wagtendonk. 2014. Temperate and Boreal Forest Mega-Fires: Characteristics and Challenges. Frontiers in Ecology and the Environment 12(2):115-122.
 - Stephens, S.L, J.D. McIver, R.E.J. Boerner, C.J. Fettig, J.B. Fontaine, B.R. Hartsough, P.I. Kennedy, and D.W. Schwilk. 2012. The Effects of Forest Fuel-Reduction Treatments in the United States. BioScience 62(6):549-560.
 - Stewart, I.T. 2009. Changes in Snowpack and Snowmelt Runoff for Key Mountain Regions. Hydrological Processes 23:78-94. DOI: 10.1002/hyp.7128
 - Stillwater Sciences. 2012. Analysis of Long-term River Regulation Effects on Genetic Connectivity of Foothill Yellow-legged Frogs (*Rana boylii*) in the Alameda Creek Watershed. Final Report. Prepared by Stillwater Sciences, Berkeley, CA for SFPUC, San Francisco, CA. 
 - Stopper, G.F., L. Hecker, R.A. Franssen, and S.K. Sessions. 2002. How Trematodes Cause Limb Deformities in Amphibians. Journal of Experimental Zoology Part B (Molecular and Developmental Evolution) 294:252-263.
 - Storer, T.I. 1923. Coastal Range of Yellow-legged Frog in California. Copeia 114:8.
 - Storer, T.I. 1925. A Synopsis of the Amphibia of California. University of California Publication Zoology 27:1-342.
 - Sweet, S.S. 1983. Mechanics of a Natural Extinction Event: Rana boylii in Southern California. Abstract of paper presented at the Joint Annual Meeting of the Herpetologists’ League and Society for the Study of Amphibians and Reptiles 7-12 August 1983, Salt Lake City, UT.
 - Syphard, A.D., V.C. Radeloff, T.J. Hawbaker, and S.I. Stewart. 2009. Conservation Threats Due to Human-Caused Increases in Fire Frequency in Mediterranean-Climate Ecosystems. Conservation Biology 23(3):758–769. DOI: 10.1111/j.1523-1739.2009.01223.x
 - Syphard, A.D., V.C. Radeloff, J.E. Keeley, T.J. Hawbaker, M.K. Clayton, S.I. Stewart, and R.B. Hammer. 2007. Human Influence on California Fire Regimes. Ecological Applications 17(5):1388-1402.

### T-U
 - Taylor, P.D., L. Fahrig, K. Henein, and G. Merriam. 1993. Connectivity Is a Vital Element of Landscape Structure. Oikos 68(3):571-573.
 - Thompson, C., R. Sweitzer, M. Gabriel, K. Purcell, R. Barrett, and R. Poppenga. 2014. Impacts of Rodenticide and Insecticide Toxicants from Marijuana Cultivation Sites on Fisher Survival Rates in the Sierra National Forest, California. Conservation Letters 7(2):91-102.
 - Thomson, R.C., A.N. Wright, and H.B. Shaffer. 2016. California Amphibian and Reptile Species of Special Concern. University of California Press, Berkeley, CA.
 - Thorne, J.H., R.M. Boynton, A.J. Holguin, J.A.E. Stewart, and J. Bjorkman. 2016. A Climate Change Vulnerability Assessment of California’s Terrestrial Vegetation. California Department of Fish and Wildlife, Sacramento, CA.
 - Tracey, J.A., C.J. Rochester, S.A. Hathaway, K.L. Preston, A.D. Syphard, A.G. Vandergast, J.E. Diffendorfer, J. Franklin, J.B. MacKenzie, T.A. Oberbauer, S. Tremor, C.S. Winchell, and R.N. Fisher. 2018. Prioritizing Conserved Areas Threatened by Wildfire and Fragmentation for Monitoring and Management. PLoS ONE 13(9):e0200203. https://doi.org/10.1371/journal.pone.0200203
 - Troïanowski, M., N. Mondy, A. Dumet, C. Arcajo, and T. Lengagne. 2017. Effects of Traffic Noise on Tree Frog Stress Levels, Immunity, and Color Signaling. Conservation Biology 31(5):1132-1140.
 - Twitty, V.C., D. Grant, and O. Anderson. 1967. Amphibian Orientation: An Unexpected Observation. Science 155(3760):352-353.
 - Unrine, J.M., C.H. Jagoe, W.A. Hopkins, and H.A. Brant. 2004. Adverse Effects of Ecologically Relevant Dietary Mercury Exposure in Southern Leopard Frog (*Rana sphenocephala*) Larvae. Environmental Toxicology and Chemistry 23(12):2964-2970.
 - U.S. Fish and Wildlife Service [USFWS]. 1998. Recovery Plan for the Shasta Crayfish (*Pacifastacus fortis*). U.S. Fish and Wildlife Service, Portland, OR.
 - U.S. Fish and Wildlife Service [USFWS]. 2015. Endangered and Threatened Wildlife and Plants; 90-Day Findings on 31 Petitions. Federal Register 80(126):37568-37579.
 - U.S. Fish and Wildlife Service. 2021. Endangered and Threatened Wildlife and Plants; Foothill Yellow-Legged Frog; Threatened Status With Section 4(d) Rule for Two Distinct Population Segments and Endangered Status for Two Distinct Population Segments. Federal register 86:73914–73945.
 - U.S. Fish and Wildlife Service [USFWS] and Hoopa Valley Tribe. 1999. Trinity River Flow Evaluation. Final Report. U.S. Fish and Wildlife Service, Arcata, CA.
 - U.S. Forest Service [USFS]. 2004. Sierra Nevada Forest Plan Amendment. Final Supplemental Environmental Impact Statement, Record of Decision.
 - U.S. Forest Service [USFS] and Bureau of Land Management [BLM]. 1994. Standards and guidelines for management of habitat for Late-Successional and Old-Growth Forest Related Species within the Range of the Northern Spotted Owl.

### V-Z
 - Van Wagner, T.J. 1996. Selected Life-History and Ecological Aspects of a Population of Foothill Yellow-legged Frogs (*Rana boylii*) from Clear Creek, Nevada County, California. Master’s Thesis. California State University Chico, Chico, CA.
 - Volpe, R.J., III, R. Green, D. Heien, and R. Howitt. 2010. Wine-Grape Production Trends Reflect Evolving Consumer Demand over 30 Years. California Agriculture 64(1):42-46.
 - Wang, I.J., J.C. Brenner, and V. Bustic. 2017. Cannabis, an Emerging Agricultural Crop, Leads to Deforestation and Fragmentation. Frontiers in Ecology and the Environment 15(9):495-501. DOI: 10.1002/fee.1634
 - Warren, D.L., A.N. Wright, S.N. Seifert, and H.B. Shaffer. 2014. Incorporating Model Complexity and Spatial Sampling Bias into Ecological Niche Models of Climate Change Risks Faced by 90 California Vertebrate Species of Concern. Diversity and Distributions 20:334-343. DOI: 10.1111/ddi.12160
 - Welsh, H.H., Jr., and G.R. Hodgson. 2011. Spatial Relationships in a Dendritic Network: The Herpetofaunal Metacommunity of the Mattole River Catchment of Northwest California. Ecography 34:49-66. DOI: 10.1111/j.1600-0587.2010.06123.x
 - Welsh, H.H., Jr., G.R. Hodgson, and A.J. Lind. 2005. Ecography of the Herpetofauna of a Northern California Watershed: Linking Species Patterson to Landscape Processes. Ecography 23:521-536.
 - Welsh, H.H., Jr., and L.M. Ollivier. 1998. Stream Amphibians as Indicators of Ecosystem Stress: A Case Study from California’s Redwoods. Ecological Applications 8(4):1118-1132.
 - Werschkul, D.F., and M.T. Christensen. 1977. Differential Predation by *Lepomis macrochirus* on the Eggs and Tadpoles of Rana. Herpetologica 33(2):237-241.
 - Westerling, A.L., H.G. Hidalgo, D.R. Cayan, and T.W. Swetnam. 2006. Warming and Earlier Spring Increase Western U.S. Forest Wildfire Activity. Science 313(5789):940-943. DOI: 10.1126/science.1128834
 - Wheeler, C.A., J.B. Bettaso, D.T. Ashton and H.H. Welsh, Jr. 2014. Effects of Water Temperature on Breeding Phenology, Growth, and Metamorphosis of Foothill Yellow-legged Frogs (*Rana boylii*): A Case Study of the Regulated Mainstem and Unregulated Tributaries of California's Trinity River. River Research and Applications 31:1276-1286. DOI: 10.1002/rra.2820
 - Wheeler, C.A., J.M. Garwood, and H.H. Welsh, Jr. 2005. *Rana boylii* (Foothill Yellow-legged Frog). Physiological Skin Color Transformation. Herpetological Review 36(2):164-165.
 - Wheeler, C.A., A.J. Lind, H.H. Welsh, Jr., and A.K. Cummings. 2018. Factors that Influence the Timing of Calling and Oviposition of a Lotic Frog in Northwestern California. Journal of Herpetology 52(3):289-298.
 - Wheeler, C.A., and H.H. Welsh, Jr. 2008. Mating Strategy and Breeding Patterns of the Foothill Yellow-legged Frog (*Rana boylii*). Herpetological Conservation and Biology 3(2):128-142.
 - Wheeler, C.A., H.H. Welsh, Jr., and T. Roelofs. 2006. Oviposition Site Selection, Movement, and Spatial Ecology of the Foothill Yellow-legged Frog (*Rana boylii*). Final Report to the California Department of Fish and Game Contract No. P0385106, Sacramento, CA.
 - Williams, A.P., R. Seager, J.T. Abatzoglou, B.I. Cook, J.E. Smerdon, and E.R. Cook. 2015. Contribution of Anthropogenic Warming to California Drought During 2012–2014. Geophysical Research Letters 42:6819-6828. DOI: 10.1002/2015GL064924
 - Williams S.E., L.P. Shoo, J.L. Isaac, A.A. Hoffmann, and G. Langham. 2008. Towards an Integrated Framework for Assessing the Vulnerability of Species to Climate Change. PLoS Biol 6(12):e325. DOI: 10.1371/journal.pbio.0060325
 - Wiseman, K.D., and J. Bettaso. 2007. *Rana boylii* (Foothill Yellow-legged Frog). Cannibalism and Predation. Herpetological Review 38(2):193.
 - Wiseman, K.D., K.R. Marlow, R.E. Jackman, and J.E. Drennan. 2005. *Rana boylii* (Foothill Yellow-legged Frog). Predation. Herpetological Review 36(2):162-163.
 - Wright, A.N., R.J. Hijmans, M.W. Schwartz, and H.B. Shaffer. 2013. California Amphibian and Reptile Species of Future Concern: Conservation and Climate Change. Final Report to the California Department of Fish and Wildlife. Contract No. P0685904, Sacramento, CA.
 - Yap, T.A., M.S. Koo, R.F. Ambrose, and V.T. Vredenburg. 2018. Introduced Bullfrog Facilitates Pathogen Invasion in the Western United States. PLoS ONE 13(4):e0188384. https://doi.org/10.1371/journal.pone.0188384 
 - Yarnell, S.M. 2005. Spatial Heterogeneity of *Rana boylii* Habitat: Physical Properties, Quantification and Ecological Meaningfulness. PhD Dissertation. University of California, Davis. 
 - Yarnell, S.M., J.H. Viers, and J.F. Mount. 2010. Ecology and Management of the Spring Snowmelt Recession. Bioscience 60(2):114-127.
 - Yoon, J-H., S-Y.S. Wang, R.R. Gillies, B. Kravitz, L. Hipps, and P.J. Rasch. 2015. Increasing Water Cycle Extremes in California and in Relation to ENSO Cycle under Global Warming. Nature Communications 6:8657. DOI: 10.1038/ncomms9657
 - Young, C.A., M. Escobar, M. Fernandes, B. Joyce, M. Kiparsky, J.F. Mount, V. Mehta, J.H. Viers, and D. Yates. 2009. Modeling the Hydrology of California’s Sierra Nevada for Sub-Watershed Scale Adaptation to Climate Change. Journal of American Water Resources Association 45:1409-1423.
 - Zhang, H., C. Cai, W. Fang, J. Wang, Y. Zhang, J. Liu, and X. Jia. 2013. Oxidative Damage and Apoptosis Induced by Microcystin-LR in the Liver of *Rana nigromaculata* in Vivo. Aquatic Toxicology 140-141:11-18.
 - Zillioux, E.J., D.B. Porcella, and J.M. Benoit. 1993. Mercury Cycling and Effects in Freshwater Wetland Ecosystems. Environmental Toxicology and Chemistry 12:2245-2264. 
 - Zweifel, R.G. 1955. Ecology, Distribution, and Systematics of Frogs of the *Rana boylei* Group. University of California Publications in Zoology 54(4):207-292.
 - Zweifel, R.G. 1968. *Rana boylii* Baird, Foothill Yellow-legged Frog. Catalogue of American Amphibians and Reptiles. Pp. 71.1-71.2.

## Unsorted

Alvarez, J. A., L. L. Surber, E. A. Gallanty, and J. T. Wilcox. 2022. Small size of Rana boylii (Anura: Ranidae) at metamorphosis in a seasonal stream may confound survey methods. Herpetology Notes.

Bedwell, M. E. 2018, May. Using genetic tools to investigate distribution and connectivity of two Sierra Nevada amphibians, Rana sierrae and Rana boylii. MSc, Washington State University, Pullman, WA.

Bondi, C. A., S. M. Yarnell, and A. J. Lind. 2013. Transferability of habitat suitability criteria for a stream breeding frog (Rana boylii) in the Sierra Nevada, California. Conservation and Biology 8:88–103.

Bursey, C. R., S. R. Goldberg, and J. B. Bettaso. 2010. Persistence and Stability of the Component Helminth Community of the Foothill Yellow-Legged Frog, Rana boylii (Ranidae), from Humboldt County, California, 1964-1965, Versus 2004-2007. The American midland naturalist 163:476–482.

Catenazzi, A., and S. J. Kupferberg. 2017. Variation in thermal niche of a declining river-breeding frog: From counter-gradient responses to population distribution patterns. Freshwater biology 62:1255–1265.

Goldberg, S. R. 2019. Notes on reproduction of the foothill yellow-legged frog, Rana boylii (Anura: Ranidae) from California. Sonoran Herpetologist 32:43–45.

Hothem, R. L., A. M. Meckstroth, K. E. Wegner, M. R. Jennings, and J. J. Crayon. 2009. Diets of Three Species of Anurans from the Cache Creek Watershed, California, USA. Journal of herpetology 43:275–283.

Kupferberg, S. J., H. Moidu, A. J. Adams, A. Catenazzi, M. Grefsrud, S. Bobzien, R. Leidy, and S. M. Carlson. 2021. Seasonal drought and its effects on frog population dynamics and amphibian disease in intermittent streams. Ecohydrology.

Leidy, R. A., E. Gonsolin, and G. A. Leidy. 2009. Late-Summer Aggregation of the Foothill Yellow-Legged Frog (Rana boylii) in Central California. The Southwestern naturalist 54:367–368.

Lind, A. J., J. B. Bettaso, and S. M. Yarnell. 2003. Rana boylii (foothill yellow-legged frog). Reproductive behavior. Herpetological Review. 34:234–235.

MacTague, L., and P. Northern. 2010. Underwater Vocalization by the Foothill Yellow-Legged Frog (Rana boylii). Transactions of the Western Section of the Wildlife Society 29:1–8.

Marlow, K. R., K. D. Wiseman, C. A. Wheeler, J. E. Drennan, and R. E. Jackman. 2016. Identification of Individual Foothill Yellow-Legged Frogs (Rana boylii) using Chin Pattern Photographs: a Non-Invasive and Effective Method for Small Population Studies. Herpetological review 47:193–198.

Moyle, P. B. 1973. Effects of Introduced Bullfrogs, Rana catesbeiana, on the Native Frogs of the San Joaquin Valley, California. Copeia 1973:18–22.

Paoletti, D. J., D. H. Olson, and A. R. Blaustein. 2011. Responses of Foothill Yellow-legged Frog (Rana boylii) Larvae to an Introduced Predator. Copeia 2011:161–168.

Poorten, T. J., E. B. Rosenblum, and R. A. Knapp. 2013. Molecular analysis of the Spanish Creek Rana population (Plumas County, California) supports taxonomic placement within Rana boylii. Report to the California Department of Fish and Wildlife. Sacramento, CA.

Rose, J. P., S. J. Kupferberg, C. A. Wheeler, P. M. Kleeman, and B. J. Halstead. 2021. Estimating the survival of unobservable life stages for a declining frog with a complex life history. Ecosphere 12.

Wheeler, C. 2007. Temporal breeding patterns and mating strategy of the Foothill yellow-legged frog (Rana boylii). M.Sci., Humbold State University, California, USA.




<!--
## Data
### Dataset


{{< downloadthis https://github.com/ryanpeek/rabo-workshop/raw/main/data/cereal.csv dname="cereal.csv" label="Download Data" icon="database-fill-down" type="info" >}}

```{r}
#| echo: false
#| message: false

readr::read_csv("../data/cereal.csv")
```
-->

## References

---
nocite: |
  @*
---